insert into projects (id, project_id, projectTitle, projectOrganisation, projectDetails, projectValue, fundingRequired, country, address, latitude, longitude, sdg1, sdg6, sdg9) values (16, 1, 'Well building in Syria', 'Oxfam', 'The Water Project digs wells in Syria to provide clean, safe water to those who need it most.', '£1468708.23', '£126174.54', 'Syria', '97 Fulton Park', 35.31025, 36.11523, 1, 6, 9);
insert into projects (id, project_id, projectTitle, projectOrganisation, projectDetails, projectValue, fundingRequired, country, address, latitude, longitude, sdg1, sdg6, sdg9) values (40, 2, 'Food for all 2023', 'MSF', 'Food Africa Project is an innovate public-private partnership between the United Nations Sustainable Development Goals Fund (SDG Fund) , Sahara Group- a member of the SDG Fund Private Sector Advisory Group (PSAG) , United Nation agencies, world renowned chefs- the Roca Brothers and the Kaduna State Governmen', '£1967798.87', '£77836.57', 'Poland', '6 Luster Plaza', 52.8517028, 16.5231662, 1, 6, 9);
insert into projects (id, project_id, projectTitle, projectOrganisation, projectDetails, projectValue, fundingRequired, country, address, latitude, longitude, sdg1, sdg6, sdg9) values (48, 3, 'Literacy for all, Jaipur', 'ReadingWeek', 'The three-month intensive digital literacy programme equips them with basic skills in operating computer software and smartphone applications. The objective? Imparting skills to increase employability opportunities for the trainees and also to prepare them for the competitive Rajasthan State Certificate in Information Technology exams for securing IT-based public sector jobs.', '£620922.08', '£1608630.93', 'Russia', '0 Esch Place', 44.0427429, 44.549842, 1, 6, 9);
insert into projects (id, project_id, projectTitle, projectOrganisation, projectDetails, projectValue, fundingRequired, country, address, latitude, longitude, sdg1, sdg6, sdg9) values (12, 4, 'Health training, medicine drive', 'NHS(Internaional)', 'The training program will be delivered through an application and aims to reach 600,000 healthcare workers — mainly nurses, doctors and midwives. The program includes six different modules available in three different languages: English, French and Arabic.', '£1932992.16', '£740114.21', 'Canada', '155 Buena Vista Road', 49.7154966, -112.6338496, 1, 6, 9);
insert into projects (id, project_id, projectTitle, projectOrganisation, projectDetails, projectValue, fundingRequired, country, address, latitude, longitude, sdg1, sdg6, sdg9) values (84, 5, 'Water wells for Micronesia', 'WWF', 'Mkwanda has 42 households or families.  There are 7 other villages that utilize the current water source with a total of 87 households.
When the new borehole is hopefully installed in this village area, 142 families are expected to benefit from it with a population of around 600 people.  The next borehole from this village is 2.5 kms or 1.6 miles away.', '£1103738.36', '£1289396.27', 'Micronesia', '1 Lyons Center', 7.3760605, 151.8843916, 1, 6, 9);
insert into projects (id, project_id, projectTitle, projectOrganisation, projectDetails, projectValue, fundingRequired, country, address, latitude, longitude, sdg1, sdg6, sdg9) values (97, 6, 'Affordable and clean energy', 'Shell (International Projects)', 'Through building a partnership between the public and private sectors, the city of Kumbasa has improved the energy efficiency of its housing stock, decreased fuel poverty and created jobs and training opportunities for vulnerable young people.', '£265454.59', '£1627146.86', 'Ethiopia', '4 Talmadge Junction', 9.7970175, 35.0993687, 1, 6, 9);
-- insert into projects (id, project_id, projectTitle, projectOrganisation, projectDetails, projectValue, fundingRequired, country, address, latitude, longitude, sdg1, sdg6, sdg9) values (35, 7, 'Medicated Pain', 'Quinu', 'Car driver injured in collision w pedal cycle nontraf, subs', '£241838.57', '£150825.12', 'Sweden', '672 Union Lane', 59.4015532, 18.3427724, 1, 6, 9);
-- insert into projects (id, project_id, projectTitle, projectOrganisation, projectDetails, projectValue, fundingRequired, country, address, latitude, longitude, sdg1, sdg6, sdg9) values (37, 8, 'L OCCITANE AU BRESIL - JENIPAPO Protecting Body SPF 15 Broad Spectrum', 'Voolia', 'Unsp fracture of left forearm, subs for clos fx w routn heal', '£1850636.53', '£1222615.94', 'Brazil', '0 Crest Line Street', -22.4206096, -41.8625084, 1, 6, 9);
-- insert into projects (id, project_id, projectTitle, projectOrganisation, projectDetails, projectValue, fundingRequired, country, address, latitude, longitude, sdg1, sdg6, sdg9) values (27, 9, 'Original Texture, Orange Flavor', 'Vimbo', 'Osteitis deformans in neoplastic diseases, left ank/ft', '£1197519.74', '£255634.39', 'Canada', '568 Anderson Lane', 49.2574664, -123.0419607, 1, 6, 9);
-- insert into projects (id, project_id, projectTitle, projectOrganisation, projectDetails, projectValue, fundingRequired, country, address, latitude, longitude, sdg1, sdg6, sdg9) values (48, 10, 'Levothyroxine sodium', 'Skyba', 'Nondisp fx of base of 5th MC bone. l hand, 7thD', '£1227950.66', '£854392.19', 'Russia', '769 Warbler Hill', 46.4144282, 37.9579616, 1, 6, 9);
